services:
  web:
    build: .
    image: "soro08/techyao"
    container_name: techyao
    command: ["sh", "./start.sh"]
    ports:
      - "8001:8005"
    volumes:
      - .:/web
      - staticfiles:/web/staticfiles
    env_file:
      - ./.env
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


volumes:
    postgres_data:
    staticfiles: