name: ci-cd

on:
    push:

env:
    # DB
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    SQL_PORT: ${{ secrets.SQL_PORT }}

    # docker registry
    DOCKER_USER: ${{secrets.DOCKER_USER}}
    DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    REGISTRY: docker.io

jobs:
    quality-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
            - name: Set env file
              run: |
                  chmod +x ./setup_env.sh
                  bash ./setup_env.sh
                  
            - run: pip install flake8
            - run: pip install black
            - run: pip install setuptools>=65.5.1 wheel>=0.38.1
            - run: pip install -r requirements.txt # install all our dependencies for the project
            - name: run flake8
              run: flake8 .
            - name: run black
              run: |
                  black . -l 129 --extend-exclude ".*\b(migrations)\b.*" --check

    unit-testing:
        runs-on: ubuntu-latest
        needs: quality-code
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
            - name: Set env file
              run: |
                  chmod +x ./setup_env.sh
                  bash ./setup_env.sh
                
            - run: pip install setuptools>=65.5.1 wheel>=0.38.1
            - run: pip install -r requirements.txt # install all our dependencies for the project
            - run: python manage.py test


    build-and-push:
        runs-on: ubuntu-latest
        needs: unit-testing
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: Set env file
              run: |
                  chmod +x ./setup_env.sh
                  bash ./setup_env.sh
            - name: docker login
              run: | # log into docker hub account
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY

            - name: Build docker compose
              run: docker compose -f docker-compose.yml build
            - name: Push all images to Docker Hub
              run: docker compose -f docker-compose.yml push

    befor-deploy:
        name: Before deploy
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: build-and-push
        steps:
            - uses: actions/checkout@v3
            - name: Set env file
              run: |
                  chmod +x ./setup_env.sh
                  bash ./setup_env.sh
            - name: copy file frim ssh key
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{secrets.DEPLOY_PUBLIC_IP_ADDRESS}}
                  username: ${{secrets.SERVER_USER}}
                  key: ${{secrets.PRIVATE_KEY}}
                  port: 22
                  source: "./.env, ./docker-compose.prod.yml"
                  target: "/${{secrets.SERVER_USER}}/techyao/"

    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: befor-deploy
        steps:
            - uses: actions/checkout@v3
            - name: docker login
              run: | # log into docker hub account
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.DEPLOY_PUBLIC_IP_ADDRESS}}
                  username: ${{secrets.SERVER_USER}}
                  key: ${{secrets.PRIVATE_KEY}}
                  port: 22
                  script: |
                      cd /${{secrets.SERVER_USER}}/techyao/
                      docker-compose -f docker-compose.prod.yml down || true
                      export $(cat .env | xargs)
                      docker rm -vf $(docker ps --filter status=exited -aq) || true                 
                      docker image prune -f -a || true
                      docker-compose -f docker-compose.prod.yml up -d